"""initial schema

Revision ID: 639cb7baf8d8
Revises: 
Create Date: 2026-09-09 01:34:44.598448

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '639cb7baf8d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('primary_identity', sa.String(length=300), nullable=True),
    sa.Column('supporting_identities', sa.JSON(), nullable=True),
    sa.Column('personality_traits', sa.JSON(), nullable=True),
    sa.Column('brand_goal', sa.Text(), nullable=True),
    sa.Column('audience_primary_age', sa.String(length=50), nullable=True),
    sa.Column('audience_primary_interests', sa.JSON(), nullable=True),
    sa.Column('audience_primary_geography', sa.JSON(), nullable=True),
    sa.Column('private_topics', sa.JSON(), nullable=True),
    sa.Column('style_boundaries', sa.JSON(), nullable=True),
    sa.Column('sponsorship_exclusions', sa.JSON(), nullable=True),
    sa.Column('current_phase', sa.String(length=100), nullable=True),
    sa.Column('strategic_priorities', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id')
    )
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'TIKTOK', 'YOUTUBE', name='platform'), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('niche', sa.String(length=200), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'TIKTOK', 'YOUTUBE', name='platform'), nullable=True),
    sa.Column('platform_user_id', sa.String(length=200), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=300), nullable=True),
    sa.Column('contact_type', sa.String(length=50), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('niche', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('total_interactions', sa.Integer(), nullable=False),
    sa.Column('first_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audience_overlap_score', sa.Float(), nullable=True),
    sa.Column('collaboration_potential', sa.Float(), nullable=True),
    sa.Column('relationship_status', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_collab', 'contacts', ['collaboration_potential'], unique=False)
    op.create_index('ix_contacts_creator', 'contacts', ['creator_id'], unique=False)
    op.create_table('content_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('episode_count', sa.Integer(), nullable=False),
    sa.Column('avg_performance_vs_median', sa.Float(), nullable=True),
    sa.Column('momentum', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('account_status', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_observation', sa.Text(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('opportunities', sa.JSON(), nullable=True),
    sa.Column('full_brief', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_briefs_date', 'daily_briefs', ['creator_id', 'date'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'RUNNING', 'COMPLETED', 'INCONCLUSIVE', name='experimentstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('confounders', sa.Text(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('autonomy_level', sa.Enum('ADVISER', 'COPILOT', 'MANAGER', 'LIMITED_AUTOPILOT', name='autonomylevel'), nullable=False),
    sa.Column('auto_approve_reads', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_analytics', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_drafts', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_profile_changes', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_posts', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_deletes', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id')
    )
    op.create_table('manager_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_type', sa.Enum('FACT', 'OBSERVATION', 'HYPOTHESIS', name='knowledgetype'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('evidence_post_ids', sa.JSON(), nullable=True),
    sa.Column('contradicting_post_ids', sa.JSON(), nullable=True),
    sa.Column('metrics_considered', sa.JSON(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('promoted_from_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['promoted_from_id'], ['manager_memory.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['manager_memory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_active', 'manager_memory', ['creator_id', 'is_active'], unique=False)
    op.create_index('ix_memory_creator_category', 'manager_memory', ['creator_id', 'category'], unique=False)
    op.create_index('ix_memory_knowledge_type', 'manager_memory', ['creator_id', 'knowledge_type'], unique=False)
    op.create_table('monetisation_readiness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('affiliate_readiness', sa.Float(), nullable=True),
    sa.Column('sponsorship_readiness', sa.Float(), nullable=True),
    sa.Column('digital_product_readiness', sa.Float(), nullable=True),
    sa.Column('coaching_readiness', sa.Float(), nullable=True),
    sa.Column('youtube_readiness', sa.Float(), nullable=True),
    sa.Column('community_readiness', sa.Float(), nullable=True),
    sa.Column('recommended_next_stream', sa.String(length=200), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('premature_warning', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('growth_assessment', sa.Text(), nullable=True),
    sa.Column('audience_quality', sa.Text(), nullable=True),
    sa.Column('brand_recognition', sa.Text(), nullable=True),
    sa.Column('platform_comparison', sa.Text(), nullable=True),
    sa.Column('niche_balance', sa.Text(), nullable=True),
    sa.Column('sentiment_analysis', sa.Text(), nullable=True),
    sa.Column('monetisation_readiness', sa.Text(), nullable=True),
    sa.Column('collaboration_review', sa.Text(), nullable=True),
    sa.Column('positioning_changes', sa.Text(), nullable=True),
    sa.Column('strategic_recommendations', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objective_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('target_mix', sa.JSON(), nullable=False),
    sa.Column('actual_mix', sa.JSON(), nullable=True),
    sa.Column('deviation_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'TIKTOK', 'YOUTUBE', name='platform'), nullable=False),
    sa.Column('platform_user_id', sa.String(length=200), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_user_id')
    )
    op.create_table('sponsorships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=300), nullable=False),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('INQUIRY', 'EVALUATING', 'NEGOTIATING', 'ACCEPTED', 'DECLINED', 'IN_PROGRESS', 'DELIVERED', 'PAID', name='sponsorshipstatus'), nullable=False),
    sa.Column('offered_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('counter_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deliverables', sa.Text(), nullable=True),
    sa.Column('usage_rights', sa.Text(), nullable=True),
    sa.Column('exclusivity', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('brand_fit_score', sa.Float(), nullable=True),
    sa.Column('audience_fit_score', sa.Float(), nullable=True),
    sa.Column('reputation_risk', sa.Float(), nullable=True),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sponsorships_creator_status', 'sponsorships', ['creator_id', 'status'], unique=False)
    op.create_table('stories_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.String(length=20), nullable=False),
    sa.Column('story_type', sa.String(length=100), nullable=False),
    sa.Column('concept', sa.Text(), nullable=True),
    sa.Column('objective', sa.String(length=100), nullable=True),
    sa.Column('was_posted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'TIKTOK', 'YOUTUBE', name='platform'), nullable=True),
    sa.Column('trend_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.Column('kobby_fit', sa.Float(), nullable=True),
    sa.Column('audience_fit', sa.Float(), nullable=True),
    sa.Column('originality_potential', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trends_creator_rec', 'trends', ['creator_id', 'recommendation'], unique=False)
    op.create_table('weekly_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('what_worked', sa.JSON(), nullable=True),
    sa.Column('what_failed', sa.JSON(), nullable=True),
    sa.Column('why_analysis', sa.Text(), nullable=True),
    sa.Column('audience_changes', sa.Text(), nullable=True),
    sa.Column('competitor_changes', sa.Text(), nullable=True),
    sa.Column('brand_health', sa.Text(), nullable=True),
    sa.Column('experiment_results', sa.JSON(), nullable=True),
    sa.Column('series_performance', sa.JSON(), nullable=True),
    sa.Column('growth_summary', sa.Text(), nullable=True),
    sa.Column('stop', sa.JSON(), nullable=True),
    sa.Column('start', sa.JSON(), nullable=True),
    sa.Column('continue_doing', sa.JSON(), nullable=True),
    sa.Column('next_week_strategy', sa.Text(), nullable=True),
    sa.Column('next_week_calendar', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('followers', sa.BigInteger(), nullable=True),
    sa.Column('followers_delta', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('total_reach', sa.BigInteger(), nullable=True),
    sa.Column('total_impressions', sa.BigInteger(), nullable=True),
    sa.Column('profile_visits', sa.Integer(), nullable=True),
    sa.Column('profile_to_follow_rate', sa.Float(), nullable=True),
    sa.Column('audience_top_countries', sa.JSON(), nullable=True),
    sa.Column('audience_top_cities', sa.JSON(), nullable=True),
    sa.Column('audience_age_gender', sa.JSON(), nullable=True),
    sa.Column('audience_active_hours', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date')
    )
    op.create_index('ix_account_metrics_date', 'account_metric_snapshots', ['account_id', 'date'], unique=False)
    op.create_table('collaboration_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('concept', sa.Text(), nullable=True),
    sa.Column('audience_overlap', sa.Float(), nullable=True),
    sa.Column('content_compatibility', sa.Float(), nullable=True),
    sa.Column('brand_safety', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('platform_post_id', sa.String(length=200), nullable=True),
    sa.Column('post_type', sa.String(length=50), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('median_views_at_capture', sa.Integer(), nullable=True),
    sa.Column('outlier_ratio', sa.Float(), nullable=True),
    sa.Column('is_outlier', sa.Boolean(), nullable=False),
    sa.Column('outlier_analysis', sa.Text(), nullable=True),
    sa.Column('format_tags', sa.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_competitor_posts_outlier', 'competitor_posts', ['competitor_id', 'is_outlier'], unique=False)
    op.create_table('content_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('BACKLOG', 'RESEARCHING', 'SCORED', 'APPROVED', 'SCRIPTED', 'FILMING', 'EDITING', 'READY', 'PUBLISHED', 'KILLED', name='ideastatus'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('concept', sa.Text(), nullable=True),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('objective', sa.Enum('REACH', 'FOLLOWER_CONVERSION', 'AUTHORITY', 'PERSONALITY', 'COMMUNITY', 'TRUST', 'COMMERCIAL', 'EXPERIMENTAL', name='postobjective'), nullable=True),
    sa.Column('target_platforms', sa.JSON(), nullable=True),
    sa.Column('suggested_hook', sa.Text(), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('shot_list', sa.JSON(), nullable=True),
    sa.Column('estimated_duration_min', sa.Float(), nullable=True),
    sa.Column('estimated_duration_max', sa.Float(), nullable=True),
    sa.Column('caption_draft', sa.Text(), nullable=True),
    sa.Column('hashtag_suggestions', sa.JSON(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('ai_score_breakdown', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_detail', sa.Text(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('trend_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['content_series.id'], ),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_ideas_status', 'content_ideas', ['creator_id', 'status'], unique=False)
    op.create_table('experiment_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('post_ids', sa.JSON(), nullable=True),
    sa.Column('metrics_summary', sa.JSON(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posting_time_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('median_reach', sa.Float(), nullable=True),
    sa.Column('median_initial_velocity', sa.Float(), nullable=True),
    sa.Column('median_retention', sa.Float(), nullable=True),
    sa.Column('median_engagement', sa.Float(), nullable=True),
    sa.Column('median_follow_conversion', sa.Float(), nullable=True),
    sa.Column('time_matters_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(length=100), nullable=False),
    sa.Column('before_value', sa.Text(), nullable=True),
    sa.Column('after_value', sa.Text(), nullable=True),
    sa.Column('before_conversion_rate', sa.Float(), nullable=True),
    sa.Column('after_conversion_rate', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('kept_change', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recognition', sa.Float(), nullable=True),
    sa.Column('niche_clarity', sa.Float(), nullable=True),
    sa.Column('follow_proposition', sa.Float(), nullable=True),
    sa.Column('cross_platform_consistency', sa.Float(), nullable=True),
    sa.Column('social_proof', sa.Float(), nullable=True),
    sa.Column('pinned_content_quality', sa.Float(), nullable=True),
    sa.Column('grid_quality', sa.Float(), nullable=True),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_profile_scores_account', 'profile_scores', ['account_id', 'scored_at'], unique=False)
    op.create_table('profile_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_pic_url', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('follower_count', sa.BigInteger(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_profile_snapshots_account_captured', 'profile_snapshots', ['account_id', 'captured_at'], unique=False)
    op.create_table('revenue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sponsorship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['sponsorship_id'], ['sponsorships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=50), nullable=True),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'TIKTOK', 'YOUTUBE', name='platform'), nullable=True),
    sa.Column('objective', sa.Enum('REACH', 'FOLLOWER_CONVERSION', 'AUTHORITY', 'PERSONALITY', 'COMMUNITY', 'TRUST', 'COMMERCIAL', 'EXPERIMENTAL', name='postobjective'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('suggested_time', sa.String(length=20), nullable=True),
    sa.Column('is_rest_day', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calendar_date', 'content_calendar', ['creator_id', 'date'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('platform_post_id', sa.String(length=200), nullable=True),
    sa.Column('post_type', sa.Enum('REEL', 'FEED', 'STORY', 'CAROUSEL', 'TIKTOK_VIDEO', name='posttype'), nullable=False),
    sa.Column('objective', sa.Enum('REACH', 'FOLLOWER_CONVERSION', 'AUTHORITY', 'PERSONALITY', 'COMMUNITY', 'TRUST', 'COMMERCIAL', 'EXPERIMENTAL', name='postobjective'), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('local_media_path', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('content_idea_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('series_episode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['content_idea_id'], ['content_ideas.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['content_series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'platform_post_id')
    )
    op.create_index('ix_posts_objective', 'posts', ['objective'], unique=False)
    op.create_index('ix_posts_published', 'posts', ['account_id', 'published_at'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('platform_comment_id', sa.String(length=200), nullable=True),
    sa.Column('author_username', sa.String(length=200), nullable=True),
    sa.Column('author_platform_id', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('should_respond', sa.Boolean(), nullable=True),
    sa.Column('respond_reason', sa.Text(), nullable=True),
    sa.Column('suggested_response', sa.Text(), nullable=True),
    sa.Column('was_responded', sa.Boolean(), nullable=False),
    sa.Column('can_become_content', sa.Boolean(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_author', 'comments', ['author_platform_id'], unique=False)
    op.create_index('ix_comments_post', 'comments', ['post_id'], unique=False)
    op.create_index('ix_comments_should_respond', 'comments', ['should_respond'], unique=False)
    op.create_table('draft_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('draft_file_path', sa.Text(), nullable=True),
    sa.Column('opening_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('predicted_objective_fit', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('growth_loops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('trigger_post_id', sa.Integer(), nullable=False),
    sa.Column('identified_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('follow_up_post_ids', sa.JSON(), nullable=True),
    sa.Column('total_followers_gained', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['trigger_post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('hook_type', sa.String(length=100), nullable=True),
    sa.Column('retention_1s', sa.Float(), nullable=True),
    sa.Column('retention_3s', sa.Float(), nullable=True),
    sa.Column('avg_watch_time', sa.Float(), nullable=True),
    sa.Column('performance_vs_median', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hooks_creator', 'hooks', ['creator_id'], unique=False)
    op.create_table('pin_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('recommended_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('slot_1_post_id', sa.Integer(), nullable=True),
    sa.Column('slot_1_purpose', sa.String(length=100), nullable=True),
    sa.Column('slot_2_post_id', sa.Integer(), nullable=True),
    sa.Column('slot_2_purpose', sa.String(length=100), nullable=True),
    sa.Column('slot_3_post_id', sa.Integer(), nullable=True),
    sa.Column('slot_3_purpose', sa.String(length=100), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('was_applied', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['slot_1_post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['slot_2_post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['slot_3_post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hours_after_publish', sa.Float(), nullable=True),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('reach', sa.BigInteger(), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('followers_from_post', sa.Integer(), nullable=True),
    sa.Column('profile_visits_from_post', sa.Integer(), nullable=True),
    sa.Column('avg_watch_time_seconds', sa.Float(), nullable=True),
    sa.Column('retention_rate', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('audience_source', sa.JSON(), nullable=True),
    sa.Column('audience_demographics', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_metrics_post_captured', 'post_metrics', ['post_id', 'captured_at'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('evidence_post_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_memory_ids', sa.JSON(), nullable=True),
    sa.Column('metrics_considered', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_decision', sa.String(length=50), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('outcome_window_days', sa.Integer(), nullable=True),
    sa.Column('outcome_measured', sa.Boolean(), nullable=False),
    sa.Column('outcome_metrics', sa.JSON(), nullable=True),
    sa.Column('outcome_baseline_metrics', sa.JSON(), nullable=True),
    sa.Column('outcome_verdict', sa.String(length=50), nullable=True),
    sa.Column('outcome_explanation', sa.Text(), nullable=True),
    sa.Column('manager_score', sa.Float(), nullable=True),
    sa.Column('related_post_id', sa.Integer(), nullable=True),
    sa.Column('resulting_post_id', sa.Integer(), nullable=True),
    sa.Column('related_experiment_id', sa.Integer(), nullable=True),
    sa.Column('memory_created_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['memory_created_id'], ['manager_memory.id'], ),
    sa.ForeignKeyConstraint(['related_experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['related_post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['resulting_post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendations_due', 'recommendations', ['outcome_due_at', 'outcome_measured'], unique=False)
    op.create_index('ix_recommendations_outcome', 'recommendations', ['outcome_verdict'], unique=False)
    op.create_index('ix_recommendations_status', 'recommendations', ['creator_id', 'status'], unique=False)
    op.create_table('reputation_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('related_post_id', sa.Integer(), nullable=True),
    sa.Column('flag_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('was_heeded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['related_post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('segments', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('has_speech', sa.Boolean(), nullable=False),
    sa.Column('first_spoken_sentence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_table('video_visual_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('face_visible_first_2s', sa.Boolean(), nullable=True),
    sa.Column('body_visible', sa.Boolean(), nullable=True),
    sa.Column('physique_reveal', sa.Boolean(), nullable=True),
    sa.Column('shirtless', sa.Boolean(), nullable=True),
    sa.Column('location_type', sa.String(length=100), nullable=True),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.Column('other_people_visible', sa.Boolean(), nullable=True),
    sa.Column('exercise_performed', sa.String(length=200), nullable=True),
    sa.Column('camera_movement', sa.String(length=100), nullable=True),
    sa.Column('camera_angle', sa.String(length=100), nullable=True),
    sa.Column('text_overlay', sa.Boolean(), nullable=True),
    sa.Column('text_overlay_content', sa.Text(), nullable=True),
    sa.Column('first_visual_description', sa.Text(), nullable=True),
    sa.Column('editing_speed', sa.String(length=50), nullable=True),
    sa.Column('cut_count', sa.Integer(), nullable=True),
    sa.Column('has_music', sa.Boolean(), nullable=True),
    sa.Column('has_voice', sa.Boolean(), nullable=True),
    sa.Column('music_genre', sa.String(length=100), nullable=True),
    sa.Column('cta_type', sa.String(length=100), nullable=True),
    sa.Column('dominant_emotion', sa.String(length=100), nullable=True),
    sa.Column('lighting', sa.String(length=100), nullable=True),
    sa.Column('color_palette', sa.String(length=200), nullable=True),
    sa.Column('first_movement_second', sa.Float(), nullable=True),
    sa.Column('strongest_visual_second', sa.Float(), nullable=True),
    sa.Column('extra_tags', sa.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_visual_features')
    op.drop_table('transcripts')
    op.drop_table('reputation_flags')
    op.drop_index('ix_recommendations_status', table_name='recommendations')
    op.drop_index('ix_recommendations_outcome', table_name='recommendations')
    op.drop_index('ix_recommendations_due', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_post_metrics_post_captured', table_name='post_metrics')
    op.drop_table('post_metrics')
    op.drop_table('pin_recommendations')
    op.drop_index('ix_hooks_creator', table_name='hooks')
    op.drop_table('hooks')
    op.drop_table('growth_loops')
    op.drop_table('draft_reviews')
    op.drop_index('ix_comments_should_respond', table_name='comments')
    op.drop_index('ix_comments_post', table_name='comments')
    op.drop_index('ix_comments_author', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_posts_published', table_name='posts')
    op.drop_index('ix_posts_objective', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_calendar_date', table_name='content_calendar')
    op.drop_table('content_calendar')
    op.drop_table('trend_snapshots')
    op.drop_table('revenue')
    op.drop_index('ix_profile_snapshots_account_captured', table_name='profile_snapshots')
    op.drop_table('profile_snapshots')
    op.drop_index('ix_profile_scores_account', table_name='profile_scores')
    op.drop_table('profile_scores')
    op.drop_table('profile_experiments')
    op.drop_table('posting_time_analysis')
    op.drop_table('experiment_variants')
    op.drop_index('ix_content_ideas_status', table_name='content_ideas')
    op.drop_table('content_ideas')
    op.drop_index('ix_competitor_posts_outlier', table_name='competitor_posts')
    op.drop_table('competitor_posts')
    op.drop_table('collaboration_proposals')
    op.drop_index('ix_account_metrics_date', table_name='account_metric_snapshots')
    op.drop_table('account_metric_snapshots')
    op.drop_table('weekly_reviews')
    op.drop_index('ix_trends_creator_rec', table_name='trends')
    op.drop_table('trends')
    op.drop_table('stories_plans')
    op.drop_index('ix_sponsorships_creator_status', table_name='sponsorships')
    op.drop_table('sponsorships')
    op.drop_table('platform_accounts')
    op.drop_table('opportunities')
    op.drop_table('objective_portfolios')
    op.drop_table('monthly_reviews')
    op.drop_table('monetisation_readiness')
    op.drop_index('ix_memory_knowledge_type', table_name='manager_memory')
    op.drop_index('ix_memory_creator_category', table_name='manager_memory')
    op.drop_index('ix_memory_active', table_name='manager_memory')
    op.drop_table('manager_memory')
    op.drop_table('manager_configs')
    op.drop_table('experiments')
    op.drop_index('ix_briefs_date', table_name='daily_briefs')
    op.drop_table('daily_briefs')
    op.drop_table('content_series')
    op.drop_index('ix_contacts_creator', table_name='contacts')
    op.drop_index('ix_contacts_collab', table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('competitors')
    op.drop_table('brand_strategies')
    op.drop_table('creators')
    # ### end Alembic commands ###
